# Generated by Django 2.1.3 on 2018-11-30 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('HA', 'Horrow with actor'), ('HW', 'Horrow without actor'), ('PA', 'Puzzle with actor'), ('PW', 'Puzzle without actor'), ('CA', 'Comedy with actor'), ('CW', 'Comedy without actor'), ('PSA', 'Police-Spy with actor'), ('PSW', 'Police-Spy without actor'), ('KW', 'Kids Friendly')], default='CW', max_length=3)),
                ('duration', models.CharField(choices=[('60M', '60 Minutes'), ('70M', '70 Minutes'), ('80M', '80 Minutes'), ('90M', '90 Minutes'), ('90+M', '90+ Minutes')], default='60M', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.Company')),
            ],
        ),
    ]
