# Generated by Django 2.1.4 on 2019-01-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('HR', 'Horror'), ('PE', 'Puzzle'), ('CY', 'Comedy'), ('PE', 'Police-Spy'), ('KS', 'Kids Friendly')], default='CY', max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='duration',
            field=models.CharField(choices=[('60M', '60 Minutes'), ('70M', '70 Minutes'), ('80M', '80 Minutes'), ('90M', '90 Minutes'), ('90+M', '90+ Minutes')], default='60M', max_length=5),
        ),
    ]
